apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-namespace
  namespace: flux-system
spec:
  interval: 1m
  path: ./namespaces/my-namespace
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: my-namespace
